baseURL = "/"
languageCode = "utf-8"
title = "YouTube Tracking Exposed"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true
[params]
    subtitle = "YouTube"
    subsite = "youtube"
    openGraphSiteName = "YouTube Tracking Exposed"
    description = "This is a collaborative project meant to let you take back control of your data. This approach do not follow corporate methods, but as an algorithm investigator let you passively records what Youtube algorithm pick for you, and let you play with the data."
    tagline = "YouTube has the power to influence a public debate - Let's expose it together!"

[permalinks]
    posts = "/:slug/"
    data = "/:filename/" # Questo non funziona

[menu]
 [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 0
 [[menu.main]]
    name = "Impact"
    url = "/impact/"
    weight = 10

 [[menu.main]]
    name = "More"
    url = "#"
    weight = 100
 [[menu.main]]
    parent = "More"
    name = "API Documentation"
    url = "/api-documentation/"
    weight = 130
 [[menu.main]]
    name = "Get Involved"
    parent = "More"
    url = "/get-involved/"
    weight = 140
 [[menu.main]]
    name = "What We Collect"
    parent = "More"
    url = "/what-we-collect/"
    weight = 150
 [[menu.main]]
    parent = "More"
    name = "Youtuber Labor union"
    url = "/seeyou/"
    weight = 170

 [[menu.featured]]
    name = "How it works"
    url = "/preview"
    weight = -180
    pre = "/images/compare.svg"
    post = "Installation, functionalities, and offered services"
 [[menu.featured]]
    name= "weTEST#1 â€• 25 March 2020"
    url = "/wetest/1"
    pre = "/images/related.svg"
    post = "We are coordinating the first global observation of the Youtube personalization algorithm. Join us!"
    weight = -170
 [[menu.featured]]
    name = "Play with data"
    url = "/data/"
    pre = "/images/data.svg"
    post = "The lastest videos we have collected with our monitoring tools"
    weight = -160

 [[menu.footer]]
    name = "Project analysis"
    url = "/initial-analysis/"
    weight = 100
 [[menu.footer]]
    name = "Umbrella project: Tracking Exposed"
    url = "https://tracking.exposed"
    weight = 90
 [[menu.footer]]
    name = "Sponsoring project: Algorithms Exposed"
    url = "https://algorithms.exposed"
    weight = 80
